### ISSUE TITLE
Issuing after retry is optional

### ISSUE THREAD

**Issue by AGWA** [quirins/caa-test#1]
Hey, thanks for posting your CAA tests! It is great to have a second set of public CAA tests.

I have a nit regarding D4 (Not signed, timeout on CAA record).  The table says the "expected CA behavior" is "Issue after retry."  I think the table should say "Refuse or issue after retry," since CAs are permitted to be more restrictive than required.  Not issuing after a timeout is definitely the safer CA behavior, so I hate to see anything that suggests CAs are expected to do it :-)

**Comment by quirins** [comment]
Hi, you are absolutely right, tried to fix the wording in 30cfc33.
